services:
  mysql:
    image: mysql:8.0
    container_name: media_tracker_mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: media_tracker
      MYSQL_USER: media_user
      MYSQL_PASSWORD: media_password

    ports:
      - "3306:3306"

    volumes:
      - media_tracker_mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  media_tracker_mysql_data: